image: mxe-docker-image-win64

variables:
  #GIT_DEPTH: "1"
  GIT_STRATEGY: none

#before_script:
#  - cd /cc
#  - cd plugins/vombat; git pull origin master
#  - cd /cc/build-mxe
#  - make
  




build:
  stage: build

  script:
     - cd /cc/plugins/vombat; git pull origin master 
     - cd /cc/build-mxe
     - x86_64-w64-mingw32.shared-cmake .. -DOPTION_BUILD_CCVIEWER=OFF -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}
        -DINSTALL_vombat_PLUGIN=ON         
      # -DINSTALL_QANIMATION_PLUGIN=ON
      # -DINSTALL_QBLUR_PLUGIN=ON
      # -DINSTALL_QDUMMY_PLUGIN=ON
      # -DINSTALL_QEDL_PLUGIN=ON
      # -DINSTALL_QPOISSON_RECON_PLUGIN=OFF
      # -DINSTALL_QSRA_PLUGIN=ON
      # -DINSTALL_QSSAO_PLUGIN=ON
      # -DINSTALL_QCSF_PLUGIN=ON
      # -DINSTALL_QPHOTOSCAN_IO_PLUGIN=ON
      # -DINSTALL_QM3C2_PLUGIN=ON
      # -DINSTALL_QPCV_PLUGIN=ON ..
     - make -j 8 install
#    - cp ../plugins/vombat/fix_needed_dynamic_libs.py ${CI_PROJECT_DIR}/cc/pack
#    - cd ${CI_PROJECT_DIR}/cc/pack
#    - python fix_needed_dynamic_libs.py
    
    
  artifacts:
    paths:        
    - CloudCompare
    
