image: mxe-docker-image-win64

variables:
  #GIT_DEPTH: "1"
  GIT_STRATEGY: none

before_script:
  - cd /
  - ls
  - cd /builds
  - git clone https://github.com/luca-penasa/trunk.git cc --depth=3 -b to_vombat
  - cd cc
  - cat .gitmodules
  - git submodule update --init --depth=3
  - cd plugins/vombat
  - git submodule update --init 
  - cd spc
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive




build:
  stage: build

  script:
    - cd /builds/cc
    - mkdir build-mxe
    - cd build-mxe
    - x86_64-w64-mingw32.shared-cmake .. -DOPTION_BUILD_CCVIEWER=OFF -DCMAKE_INSTALL_PREFIX=/builds/ccwin-build
      # -DINSTALL_vombat_PLUGIN=ON         
      # -DINSTALL_QANIMATION_PLUGIN=ON
      # -DINSTALL_QBLUR_PLUGIN=ON
      # -DINSTALL_QDUMMY_PLUGIN=ON
      # -DINSTALL_QEDL_PLUGIN=ON
      # -DINSTALL_QPOISSON_RECON_PLUGIN=OFF
      # -DINSTALL_QSRA_PLUGIN=ON
      # -DINSTALL_QSSAO_PLUGIN=ON
      # -DINSTALL_QCSF_PLUGIN=ON
      # -DINSTALL_QPHOTOSCAN_IO_PLUGIN=ON
      # -DINSTALL_QM3C2_PLUGIN=ON
      # -DINSTALL_QPCV_PLUGIN=ON ..
    - make -j 8 install
    - cp ../fix_needed_dynamic_libs.py /builds/ccwin-build
    - cd /builds/ccwin-build
    - python fix_needed_dynamic_libs.py
    
    
  artifacts:
    paths:    
    - ccwin-build/CloudCompare*